---
apiVersion: v1
kind: Template
metadata:
  name: ${CLUSTER_NAME}-secrets
  namespace: ${CLUSTER_NAME}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-secrets
    namespace: ${CLUSTER_NAME}
  stringData:
    .dockerconfigjson: |-
      {"auths":{THIS IS YOUR PULL SECRET}}
    aws_access_key_id: 
    aws_secret_access_key: 
    ssh-privatekey: |-
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: install-config
    namespace: ${CLUSTER_NAME}
  type: Opaque
  stringData:
  install-config.yaml: |-
      apiVersion: v1
      metadata:
        name: ${CLUSTER_NAME}
      baseDomain: ${CLUSTER_BASEDOMAIN}
      controlPlane:
        hyperthreading: Enabled
        name: master
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 100
              type: gp2
            type: m5.xlarge
        replicas: 3
      compute:
      - hyperthreading: Enabled
        name: worker
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 100
              type: gp2
            type: m5.xlarge
        replicas: 3
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineCIDR: 10.0.0.0/16
        networkType: OpenShiftSDN
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        aws:
          region: us-east-1
      pullSecret: "" # skip, hive will inject based on it's secrets
      sshKey: |-
        ssh-rsa ... your_email@example.com
parameters:
- description: The name used for this configMap cluster template
  name: CLUSTER_NAME
  required: true
- description: The basedomain registered with your cloud provider
  name: CLUSTER_BASEDOMAIN
  required: true